### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by deejay1** [kairosdb/kairos-carbon#10]
We're having performance issues when trying to run the carbon plugin ingesting our carbon data.
Right now we're at about 3 million metrics per minute on the carbon relays, and we try to forward this through a load balancer to 10 Kairos carbon ingest nodes backed by an 8 node Cassandra cluster (2 rings, 4 nodes per ring)
Unfortunately we're seeing about 700k fullQueueDrops on the relays :(
![relays](https://cloud.githubusercontent.com/assets/41211/9836826/73894af4-5a28-11e5-9f91-bdb29fcc237e.png)

When trying to debug it it looks like most of the times we aren't even hitting the messageReceived method in the CarbonPickleServer.

Any hints?

**Comment by brianhks** [comment]
I'm not a graphite expert, but I found client.py on github https://github.com/tmm1/graphite/blob/master/carbon/lib/carbon/client.py and it appears that the internal graphite queue is full, it is recieveing data faster than it can send to Kairos (that bit may be obvious).  There appears to be some flow control code in there as well and I wonder if there is a graphite setting for how fast it sends data out.

From my testing a single Kairos node should be able to handle the flow of data you have and you have 10.  What does the load look like across the system while you are loading data?

**Comment by brianhks** [comment]
Assuming this is resolved
