### ISSUE TITLE
jmxtrans-agent(graphite) -> kairos-carbon broken pipe

### ISSUE THREAD

**Issue by trikosuave** [kairosdb/kairos-carbon#11]
From my understanding, jmxtrans-agent creates a connection, sends data, then flushes any left over data. Every time jmxtrans-agent flushes I get a broken pipe. Is kairos-carbon closing the connection immediately after receiving data? Has this been tested with jmxtrans-agent (GraphitePlainTextTcpOutputWriter)?

Thanks!

**Comment by brianhks** [comment]
It worked at one time.  The server expects each message to be line delimited and continues to hold the connection open.  Try using wireshark to look at the network traffic and see what it is doing.

**Comment by trikosuave** [comment]
Not seeing anything from the broken pipe IP addresses. If I restart jmxtrans-agent, it sends metrics once and then stops, but no errors on the jmxtrans side. 
Further digging I set jmxtrans-agent to send to a local file as well. If I have it sending to both, it will send one set then stop. If I take off the Graphite output (going to kairos-carbon), the file output will go every minute like its supposed to. I'm not sure how to dignose further. I have check logs on both sides with nothing standing out. I'm checked lsof on the kairos server and it's ~300. 

Can you think of anything I can try? Thanks!

**Comment by trikosuave** [comment]
Update: left it running. It's not quitting on either end but longer than a minute between events.
```
[2015-11-19T20:42Z] type.cassandra.droppedMessageCounterMutationFiveMinuteRate 0.0
[2015-11-19T20:58Z] type.cassandra.droppedMessageCounterMutationOneMinuteRate 0.0
```
Then after the whole metrics set at 20:42 and 20:58. I got another at 20:59 and 21:00. But then it stopped again. I have 2 large servers behind a load balancer. CPU usage is low on both boxes. Do you know of any place I can check to see if something is overloaded?

**Comment by brianhks** [comment]
Given face value, what you are doing should work.  I'd have to dig into the jmx trans code to figure out why it doesn't work.  If you are not married to jmx trans, another option - which is what we use - is to use collectd and the fastjmx plugin and kairosdb writer.  With collectd you can get system metrics along with your jmx metrics.  We have it running on all of our systems.

**Comment by trikosuave** [comment]
I noticed Grafana mentions 0.9.4 specifically. 
We are noticing some wierd things in Grafana and are using kdb 1.0.1. 
Will kairos-carbon work with 0.9.4? 
Did something change in kdb from 0.9.4 to 1.1.0 that would have broken grafana?

**Comment by trikosuave** [comment]
We had our kairosdb boxes behind an ELB in AWS. If I attached one of our jmxtrans-agents directly to an IP address instead of the ELB, it seems to work. We can do that for now. 

Thanks again for all your help.
