### ISSUE TITLE
Updated release

### ISSUE THREAD

**Issue by mamoit** [kairosdb/kairos-carbon#24]
It would be very nice to have an updated release (no release has been produced for the past 2 years / 18 commits).
I'm no java developer and it a hurdle to build this project (not that I won't do it though :smile:).

**Comment by brianhks** [comment]
I'll build a release if you will test it.  I'll attach the build to this issue.

**Comment by mamoit** [comment]
I ended up building it myself with the `master` branch :slightly_smiling_face: 
Going to benchmark it tomorrow or on Friday to see how it matches the http api.

**Comment by mamoit** [comment]
Just rebuilt it with the changes that you merged into master 2 days ago, we're going to test it today.

**Comment by mamoit** [comment]
Due to time constraints, we'll have to use the HTTP API for now :neutral_face:
Didn't manage to do the benchmark, sorry.

**Comment by brianhks** [comment]
I'm just testing a new release now.  Should be out in a day or two.

**Comment by brianhks** [comment]
Just giving an update.  I finally got a test setup using collectd to send data to my code using carbon.  I've updated the code but the tests aren't all working.  Pickle doesn't seem to be working.

**Comment by brianhks** [comment]
Done
