### ISSUE TITLE
Unable to load service kairosdb.service.carbon with latest kairosdb 1.3.0 version

### ISSUE THREAD

**Issue by mdvaliyullah** [kairosdb/kairos-carbon#28]
02-03|08:36:36.777 [main] INFO  [Main.java:127] - Loading plugin properties: kairos-carbon.properties
02-03|08:36:37.037 [main] INFO  [Main.java:260] - Loading service carbon: org.kairosdb.plugin.carbon.CarbonServerModule
02-03|08:36:37.046 [main] ERROR [Main.java:296] - Unable to load service kairosdb.service.carbon

**Comment by brianhks** [comment]
Just resolved with the 1.4 update.
