### ISSUE TITLE
Support for Carbon protocols over UDP

### ISSUE THREAD

**Issue by falzm** [kairosdb/kairos-carbon#4]
Hi

As the original Carbon implementation supports receiving metrics over TCP and UDP, could you add support for UDP too? It helps when receiving metrics from hundreds of senders.

Cheers

**Comment by brianhks** [comment]
I'm adding it as part of the next release.

**Comment by falzm** [comment]
Cool, thanks!

**Comment by brianhks** [comment]
Just added,  one issue I found while testing is that you must make sure your max message size is big enough for the udp packet or it will chop it off and kairos will throw a bunch of exceptions because it cannot parse a full metric.
