### ISSUE TITLE
Ready-built Release?

### ISSUE THREAD

**Issue by efrecon** [kairosdb/kairos-carbon#6]
Would you consider making available an "official" build for the plugin so it can automatically get added to, say, a docker component?

**Comment by brianhks** [comment]
Yes, for the 1.0 release of Kairos I'll cut a build of every plugin and post them.

**Comment by efenderbosch** [comment]
Is a build available anywhere? When I checkout the source and attempt a build, Ivy tries to resolve dependencies and it never finishes.

**Comment by zbintliff** [comment]
Would also like to have the Jar on a release schedule so we can install it in a container.
