### ISSUE TITLE
Redefine "host" tag?

### ISSUE THREAD

**Issue by skeller047** [kairosdb/kairos-carbon#7]
Assuming that Graphite metrics always have the host name in the second position (as in "group.host.metric1.metric2....") is bad.  Not all Graphite metrics have a host, and not all Graphite metrics with host names place the host in the second section of the metric.  I am dealing with this by changing the metric replacement to replace the entire metric ($1.$2.$3), but there either has to be a way to not create a tag at all, or have a more complete rule-based matching scheme so that we can create tags intelligently.  Something like the native Graphite storage-schema rules, for example.

**Comment by brianhks** [comment]
I'm trying to do this so the consumer of this plugin doesn't have to write code.  You are right the matching rules may have to be more complicated.  Can you include some examples of metrics you are dealing with?

**Comment by deejay1** [comment]
One solution would be to support named capturing groups, where the group name would be the tag name. This what I'm doing right now in code (implementing a separate parser). One problem is that while tags can have underscores group names in Java don't (at least when I tried it)

**Comment by skeller047** [comment]
Brian, sorry about the delay replying.  As I have worked on this further, it has become obvious that I need to deal with multiple tags per metric, and have a schema matching algorithm (similar to the Graphite storage_schemas file) that determines tags.  

Example - collectd sends data to Graphite like this:
collectd.<host>.<metric>.<submetric>  
This would be matched by something like "^collectd\..*"

In our environment, we have multiple teams sending Graphite data with very different formats.  One that I work with is:

<dotted,prefix>.<environment>.<platform>.<host>.<dotted.metric>

environment, platform and host would be tags, the metric would be passed in as is, and the prefix would become a tag named source, possibly with a translation table.  

I would match this on the prefix, as with collectd.  

Other teams have similar data feeds, but laid out differently, perhaps not using the platform tag, perhaps using another tag like "db" or something, you get the picture.  Each Graphite data format would have to be handled separately, and it would be nice to be able to do this from a config file rather than write code for each pattern.  

I know that's a big ask, but it's what I need, and we are considering writing a custom insertion utility that translates our various Graphite feeds, using standard KairosDB data insertion at the back end.

**Comment by gauthier-delacroix** [comment]
@deejay1  @skeller047 I've just submitted a custom tag parser in #13 that could fit your needs. Please try it and comment to help me improve it !
